name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  push_to_dockerhub:
    name: Push Docker image to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: logi n to dockerhub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_KEY }}
        
      - name: build docker image
        run: |
          cd provided_files/java_sqs_client
          docker build . -t sqs_prompt_as_argument
          
        
      - name: push docker image to dockerhub
        run: |
          docker push SQS_prompt_as_argument
          
